#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math

class Router:

    relations = {}
    sockets = {}
    ports = {}

    def __init__(self, asn, connections):
        print("Router at AS %s starting up" % asn)
        self.asn = asn
        for relationship in connections:
            port, neighbor, relation = relationship.split("-")

            self.sockets[neighbor] = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.sockets[neighbor].bind(('localhost', 0))
            self.ports[neighbor] = int(port)
            self.relations[neighbor] = relation
            self.send(neighbor, json.dumps({ "type": "handshake", "src": self.our_addr(neighbor), "dst": neighbor, "msg": {}  }))
        # route entry contains: network, netmask, peer, localpref, origin, selfOrigin, ASPath
        self.forwarding_table = []; # list of dicts, each dict is a route entry
        # the two lists below are used to deaggregate entries by clearing the table and re-adding entries in the order they were received
        self.update_history = []; # history of all updates to the forwarding table
        self.withdraw_history = []; # history of all withdrawals from the forwarding table

    def our_addr(self, dst):
        quads = list(int(qdn) for qdn in dst.split('.'))
        quads[3] = 1
        return "%d.%d.%d.%d" % (quads[0], quads[1], quads[2], quads[3])

    def send(self, network, message):
        self.sockets[network].sendto(message.encode('utf-8'), ('localhost', self.ports[network]))

    # turns dotted string describing IP address into binary int
    def ip_to_bin(self, ip: str) -> int:
        octets = ip.split('.')
        A = int(octets[0])
        B = int(octets[1])
        C = int(octets[2])
        D = int(octets[3])
        return A * 256**3 + B * 256**2 + C * 256**1 + D * 256**0

    # turns binary int describing IP address into dotted string
    def bin_to_ip(self, n: int) -> str:
        n = n & 0xFFFFFFFF
        A = (n >> 24) & 0xFF
        B = (n >> 16) & 0xFF
        C = (n >> 8) & 0xFF
        D = n & 0xFF
        return "%d.%d.%d.%d" % (A, B, C, D)

    # returns how many leading 1 bits the netmask has
    def mask_len(self, netmask: str) -> int:
        mask_bin = self.ip_to_bin(netmask)
        count = 0
        while mask_bin:
            count += 1
            mask_bin= mask_bin >> 1
        return count

    # returns true if the ip is in the network defined by network address and netmask
    def is_in_ntwrk(self, ip: str, ntwrk: str, netmask: str) -> bool:
        ip_bin = self.ip_to_bin(ip)
        ntwrk_bin = self.ip_to_bin(ntwrk)
        netmask_bin = self.ip_to_bin(netmask)
        return (ip_bin & netmask_bin) == (ntwrk_bin & netmask_bin)

    # returns true if the two networks are adjacent
    def is_adjacent(self, ntwrk1, mask1, ntwrk2, mask2) -> bool:
        if self.mask_len(mask1) != self.mask_len(mask2):
            return False
        mask_len = self.mask_len(mask1)
        # build network addresses by applying the masks
        ntwrk_addr_1 = self.ip_to_bin(ntwrk1) & self.ip_to_bin(mask1)
        ntwrk_addr_2 = self.ip_to_bin(ntwrk2) & self.ip_to_bin(mask2)
        block = 2 ** (32 - mask_len)
        # check if difference between the two network addresses is equal to block size
        return abs(ntwrk_addr_1 - ntwrk_addr_2) == block

    # aggregates two networks into one network
    def aggregate(self, ntwrk1, mask1, ntwrk2, mask2) -> tuple:
        mask_len = self.mask_len(mask1)
        mask_len_new = mask_len - 1
        mask1_bin = self.ip_to_bin(mask1)
        # build network addresses by applying the masks
        ntwrk_addr_1 = self.ip_to_bin(ntwrk1) & mask1_bin
        ntwrk_addr_2 = self.ip_to_bin(ntwrk2) & self.ip_to_bin(mask2)
        aggregated_ntwrk_addr = min(ntwrk_addr_1, ntwrk_addr_2)
        # build new mask by subtracting 1 from og mask length
        new_mask_int = ((1 << 32) - (1 << (32 - mask_len_new))) & 0xFFFFFFFF
        return (self.bin_to_ip(aggregated_ntwrk_addr), self.bin_to_ip(new_mask_int))

    """
    This function handles an update message from a neightbor.
    It first appends the update to the update history,
    then constructs a route entry from the update message.
    It then determines if the entry should be forwarded to any other
    neighbors, based on the relationship between the neighbor and the router.
    """
    def update(self, srcif, msg):
        self.update_history.append({
            "srcif": srcif,
            "msg": msg
        })
        entry = {
            "network": msg["msg"]["network"],
            "netmask": msg["msg"]["netmask"],
            "peer": srcif,
            "localpref": msg["msg"]["localpref"],
            "ASPath": msg["msg"]["ASPath"],
            "origin": msg["msg"]["origin"],
            "selfOrigin": msg["msg"]["selfOrigin"]
        }
        self.forwarding_table.append(entry)
        # determine where the entry should be forwarded
        relation = self.relations[srcif]
        for n in self.sockets:
            if n == srcif:
                continue
            # customer
            if relation == "cust":
                should_send = True
            # peer or provider
            else:
                should_send = (self.relations[n] == "cust")
            if should_send:
                fwd_msg = {
                    "src": self.our_addr(n),
                    "dst": n,
                    "type": "update",
                    "msg": {
                        "network": msg["msg"]["network"],
                        "netmask": msg["msg"]["netmask"],
                        "ASPath": [self.asn] + msg["msg"]["ASPath"]
                    }
                }
                self.send(n, json.dumps(fwd_msg))


    """
    This function handles a withdrawal message from a neighbor.
    It first appends the withdrawal to the withdrawal history,
    then rebuilds the forwarding table using the update history,
    then applies the withdrawals to the forwarding table,
    then determines if the withdrawal should be forwarded to any other
    neighbors, based on the relationship between the neighbor and the router.
    If so, it sends the withdrawal to the neighbor.
    """
    def withdraw(self, srcif, msg):
        self.withdraw_history.append({
            "srcif": srcif,
            "msg": msg
        })
        # rebuild forwarding table using update history
        self.forwarding_table.clear()
        for row in self.update_history:
            m = row["msg"]
            if m["type"] == "update":
                self.forwarding_table.append({
                    "network": m["msg"]["network"],
                    "netmask": m["msg"]["netmask"],
                    "peer": row["srcif"],
                    "localpref": m["msg"]["localpref"],
                    "ASPath": m["msg"]["ASPath"],
                    "origin": m["msg"]["origin"],
                    "selfOrigin": m["msg"]["selfOrigin"]
                })
        # apply withdrawals to forwarding table
        for row in self.withdraw_history:
            withdrawn = row["msg"]["msg"]
            for w in withdrawn:
                    new_table = []
                    for r in self.forwarding_table:
                        if r["network"] != w["network"] or r["netmask"] != w["netmask"]:
                            new_table.append(r)
                    self.forwarding_table = new_table
        # same send logic as update
        relation = self.relations[srcif]
        for n in self.sockets:
            if n == srcif:
                continue
            # customer
            if relation == "cust":
                should_send = True
            # peer or provider
            else:
                should_send = (self.relations[n] == "cust")
            if should_send:
                fwd_msg = {
                    "src": self.our_addr(n),
                    "dst": n,
                    "type": "withdraw",
                    "msg": msg["msg"]
                }
                self.send(n, json.dumps(fwd_msg))


    """
    This function handles a data message from a neighbor.
    It first checks if the destination is in any of the routes in the forwarding table.
    If it is, it then uses given tiebreaker rules to select the best route.
    The function does this by scoring each route based on the tiebreaker rules
    and selecting the highest scored route.
    Finally, the function sends the data to the best route.
    """
    def data(self, srcif, msg):
        pot_routes = []
        no_route_msg = {
            "src": self.our_addr(srcif),
            "dst": msg["src"],
            "type": "no route",
            "msg": {}
        }
        for e in self.forwarding_table:
            if self.is_in_ntwrk(msg["dst"], e["network"], e["netmask"]):
                pot_routes.append(e)
        # if no potential routes, send no route message
        if not pot_routes:
            self.send(srcif, json.dumps(no_route_msg))
            return
        # strip potential routes to the one best route based on given tiebreaker rules
        origin_ranks = {"IGP": 3, "EGP": 2, "UNK": 1}
        best_route = None
        # score takes in all tiebreaker rules and rates a given route
        best_score = None

        for r in pot_routes:
            # longer prefix length is better
            p_len = self.mask_len(r["netmask"])
            # higher localpref is better
            localpref = r["localpref"]
            # self-originated routes are better
            self_origin_score = 1 if r["selfOrigin"] else 0
            # shorter AS path is better
            aspath_len = len(r["ASPath"])
            # higher rank is better
            origin_score = origin_ranks[r["origin"]]
            # lower peer IP is better
            peer_ip_score = -self.ip_to_bin(r["peer"])

            score = (
                p_len,
                localpref,
                self_origin_score,
                -aspath_len,
                origin_score,
                peer_ip_score,
            )

            if best_route is None or score > best_score:
                best_route = r
                best_score = score

        if self.relations[srcif] == "cust" or self.relations[best_route["peer"]] == "cust":
            self.send(best_route["peer"], json.dumps(msg))
        else:
            self.send(srcif, json.dumps(no_route_msg))
        

    def dump(self, srcif, msg):
        pass

    def run(self):
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                k, addr = conn.recvfrom(65535)
                srcif = None
                for sock in self.sockets:
                    if self.sockets[sock] == conn:
                        srcif = sock
                        break
                msg_str = k.decode('utf-8')
                print("Received message '%s' from %s" % (msg_str, srcif))
                # stubs for handling router features
                msg = json.loads(msg_str)
                if msg["type"] == "update":
                    self.update(srcif, msg)
                elif msg["type"] == "withdraw":
                    self.withdraw(srcif, msg)
                elif msg["type"] == "data":
                    self.data(srcif, msg)
                elif msg["type"] == "dump":
                    self.dump(srcif, msg)
        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='route packets')
    parser.add_argument('asn', type=int, help="AS number of this router")
    parser.add_argument('connections', metavar='connections', type=str, nargs='+', help="connections")
    args = parser.parse_args()
    router = Router(args.asn, args.connections)
    router.run()
